language: elixir

branch:
  only:
    - master

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.4
      script: mix test --exclude property --trace
    - otp_release: 19.3
      elixir: 1.4.4
      script: mix test --exclude property --trace
    - otp_release: 20.2
      elixir: 1.5.3
      script: mix test --trace
    - otp_release: 20.2
      elixir: 1.6.6
      script: mix test --trace
    - otp_release: 21.0
      elixir: 1.7.4
    - otp_release: 21.0
      elixir: 1.8.1
      script:
        - mix format --check-formatted
        - mix test --trace


sudo: false
